[WIP] CI: migrate pipeline into GH Actions
newrelic/nri-apache pull request #48
Opened 2020-10-14 14:22 UTC by brushknight

2020-11-05 09:01 UTC, gsanchezgavier requested changes

2020-11-05 09:01 UTC, gsanchezgavier commented on build/package/windows/nri-386-installer/Product.wxs
> +    <?define UpgradeCode = "{1a921296-1d82-4014-83ad-9d0c2f9c9bef}" ?>
upgrade code repeated with other integrations pr for the ci

2020-11-09 15:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/nri-apache?pullRequest=48) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/nri-apache?pullRequest=48) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: brushknight<br/>:x: Joan Porta<br/><hr/>**Joan Porta** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/nri-apache?pullRequest=48) it.</sub>

2021-01-12 14:15 UTC, paologallinaharbur commented
Going to close this in favor of https://github.com/newrelic/nri-apache/pull/52

2021-01-15 14:14 UTC, paologallinaharbur commented
This is ready to be reviewed

2021-01-15 14:24 UTC, roobre approved these changes
lgtm!

2021-01-15 15:53 UTC, arvdias approved these changes

2021-01-18 13:44 UTC, paologallinaharbur commented on .github/workflows/prerelease.yml
> +  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
I believe it is not, but I am not 100% sure

2021-01-18 15:04 UTC, paologallinaharbur commented on .github/workflows/prerelease.yml
> +  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret

The environment variable is not created automatically

2021-01-18 15:38 UTC, merged